from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
import os

app = FastAPI(
    title="KLS Tech Solutions API",
    description="Backend for KLS Automation Platform",
    version="0.1.0"
)

# --- 1. CORS Configuration (Crucial for Dev) ---
# Allows your React app (running on port 5173) to talk to this backend
origins = [
    "http://localhost:5173",  # Vite default
    "http://localhost:3000",  # Cra/Next default
    "http://127.0.0.1:5173",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- 2. API Routes ---
@app.get("/api/health")
async def health_check():
    return {
        "status": "active", 
        "service": "KLS Backend", 
        "mode": "R&D"
    }

# --- 3. Serve React Frontend (Production Mode) ---
# This block checks if the frontend has been built. If yes, it serves it.
# If not, it assumes you are in Dev mode running frontend separately.

# Path to the 'dist' folder generated by 'npm run build'
frontend_dist = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "frontend", "dist")

if os.path.exists(frontend_dist):
    # Mount assets (js, css, images)
    app.mount("/assets", StaticFiles(directory=os.path.join(frontend_dist, "assets")), name="assets")
    
    # Catch-all route for SPA (Single Page Application)
    # This ensures that refreshing "/custom-solutions" doesn't give a 404, 
    # but returns index.html so React Router can take over.
    @app.get("/{full_path:path}")
    async def serve_react_app(full_path: str):
        # Allow API calls to pass through
        if full_path.startswith("api/"):
            return {"error": "API endpoint not found"}
            
        return FileResponse(os.path.join(frontend_dist, "index.html"))
else:
    print(f"⚠️  Frontend build not found at: {frontend_dist}")
    print("ℹ️  Running in API-only mode. Run 'npm run dev' in frontend folder for UI.")