from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
import os

from app.core.config import CORS_ORIGINS, API_PREFIX
from app.api import home, products, solutions, about, contact

app = FastAPI(
    title="KLS Tech Solutions API",
    description="Backend for KLS Automation Platform",
    version="0.1.0"
)

# --- 1. CORS Configuration (Crucial for Dev) ---
# Allows your React app (running on port 5173) to talk to this backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- 2. API Routes ---
# Health check endpoint
@app.get(f"{API_PREFIX}/health")
async def health_check():
    return {
        "status": "active", 
        "service": "KLS Backend", 
        "mode": "R&D"
    }

# Include all API routers
app.include_router(home.router, prefix=f"{API_PREFIX}/home", tags=["home"])
app.include_router(products.router, prefix=f"{API_PREFIX}/products", tags=["products"])
app.include_router(solutions.router, prefix=f"{API_PREFIX}/solutions", tags=["solutions"])
app.include_router(about.router, prefix=f"{API_PREFIX}/about", tags=["about"])
app.include_router(contact.router, prefix=f"{API_PREFIX}/contact", tags=["contact"])

# --- 3. Serve React Frontend (Production Mode) ---
# This block checks if the frontend has been built. If yes, it serves it.
# If not, it assumes you are in Dev mode running frontend separately.

# Path to the 'dist' folder generated by 'npm run build'
frontend_dist = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "frontend", "dist")

if os.path.exists(frontend_dist):
    # Mount assets (js, css, images)
    app.mount("/assets", StaticFiles(directory=os.path.join(frontend_dist, "assets")), name="assets")
    
    # Catch-all route for SPA (Single Page Application)
    # This ensures that refreshing "/custom-solutions" doesn't give a 404, 
    # but returns index.html so React Router can take over.
    @app.get("/{full_path:path}")
    async def serve_react_app(full_path: str):
        # Allow API calls to pass through
        if full_path.startswith("api/"):
            return {"error": "API endpoint not found"}
            
        return FileResponse(os.path.join(frontend_dist, "index.html"))
else:
    print(f"⚠️  Frontend build not found at: {frontend_dist}")
    print("ℹ️  Running in API-only mode. Run 'npm run dev' in frontend folder for UI.")